### ISSUE TITLE
confusion about the shared router

### ISSUE THREAD

**Issue by Jxzh2020** [Yaxin9Luo/Gamma-MOD#6]
Hello~ 
I'm new to this MoD technique. And after reading your paper, I wonder: 
1. Though sharing router enables the router to better learn the token importance, is current simple linear projection enough for capturing different tokens' importance among different layers?
2. Is there any other attempts that have been tested out to predict the token importance among all in a certain layer of a LLM?

I'd be happy if you can give an explanation to these questions.

**Comment by Yaxin9Luo** [comment]
Sorry for late replying, quite busy last week.  Regarding your questions:
1.We have tested an alternative MLP router, while makes no difference, however, we believe there muse be better way for training an end-to-end router that capturing different tokens' importance among different layers, right now, we design a masked routing learning strategy to handle this.
2. I suggest you to read https://arxiv.org/abs/2406.15786, https://arxiv.org/abs/2410.05258, https://arxiv.org/abs/2402.17762

**Comment by Jxzh2020** [comment]
Appreciate your patient reply! Papers mentioned above truly uncover some properties hiding behind the transformer mechanism.
